// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WARDMANAGEMENTSYSTEM.Data;

#nullable disable

namespace WARDMANAGEMENTSYSTEM.Migrations
{
    [DbContext(typeof(WardDbContext))]
    partial class WardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByWardAdminId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("CreatedByWardAdminId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("AllergyId");

                    b.ToTable("AdmissionAllergies");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("ConditionId");

                    b.ToTable("AdmissionConditions");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("MedicationId");

                    b.ToTable("AdmissionMedications");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allergic to penicillin antibiotics",
                            IsActive = "Active",
                            Name = "Penicillin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Latex allergy",
                            IsActive = "Active",
                            Name = "Latex"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOccupied")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedNumber = "A-01",
                            IsActive = "Active",
                            IsOccupied = "False",
                            WardId = 1
                        },
                        new
                        {
                            Id = 2,
                            BedNumber = "A-02",
                            IsActive = "Active",
                            IsOccupied = "False",
                            WardId = 1
                        },
                        new
                        {
                            Id = 3,
                            BedNumber = "S-01",
                            IsActive = "Active",
                            IsOccupied = "False",
                            WardId = 2
                        },
                        new
                        {
                            Id = 4,
                            BedNumber = "S-02",
                            IsActive = "Active",
                            IsOccupied = "False",
                            WardId = 2
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High blood pressure",
                            IsActive = "Active",
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Non-insulin dependent diabetes",
                            IsActive = "Active",
                            Name = "Diabetes Type 2"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Consumable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = "Active",
                            Name = "Sterile Gloves",
                            QuantityOnHand = 100,
                            ReorderLevel = 20
                        },
                        new
                        {
                            Id = 2,
                            IsActive = "Active",
                            Name = "Linen Savers",
                            QuantityOnHand = 50,
                            ReorderLevel = 10
                        },
                        new
                        {
                            Id = 3,
                            IsActive = "Active",
                            Name = "Syringe 5ml",
                            QuantityOnHand = 200,
                            ReorderLevel = 50
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.ConsumableOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.ToTable("ConsumableOrders");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.DoctorVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalDoctorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsContactRecord")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorVisits");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsTwoFactorEnabled")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("MustChangePassword")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPinExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Email = "admin@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            Gender = "Male",
                            HireDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "User",
                            MustChangePassword = "False",
                            PasswordHash = "admin123",
                            Role = "ADMINISTRATOR",
                            UserName = "admin"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Email = "wardadmin@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "John",
                            Gender = "Male",
                            HireDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Doe",
                            MustChangePassword = "False",
                            PasswordHash = "wardadmin123",
                            Role = "WARDADMIN",
                            UserName = "wardadmin"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Email = "doctor@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Sarah",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Smith",
                            MustChangePassword = "False",
                            PasswordHash = "doctor123",
                            Role = "DOCTOR",
                            UserName = "doctor"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Email = "nurse@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Michael",
                            Gender = "Male",
                            HireDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Brown",
                            MustChangePassword = "False",
                            PasswordHash = "nurse123",
                            Role = "NURSE",
                            UserName = "nurse"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Email = "sister@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Emily",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Davis",
                            MustChangePassword = "False",
                            PasswordHash = "sister123",
                            Role = "NURSINGSISTER",
                            UserName = "sister"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Email = "script@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "David",
                            Gender = "Male",
                            HireDate = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Wilson",
                            MustChangePassword = "False",
                            PasswordHash = "script123",
                            Role = "SCRIPTMANAGER",
                            UserName = "script"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Email = "consum@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Laura",
                            Gender = "Female",
                            HireDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Taylor",
                            MustChangePassword = "False",
                            PasswordHash = "consum123",
                            Role = "CONSUMABLESMANAGER",
                            UserName = "consum"
                        },
                        new
                        {
                            EmployeeID = 8,
                            Email = "porter@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Robert",
                            Gender = "Male",
                            HireDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Mkhize",
                            MustChangePassword = "False",
                            PasswordHash = "porter123",
                            Role = "PORTER",
                            UserName = "porter"
                        },
                        new
                        {
                            EmployeeID = 9,
                            Email = "pharmacist@hospital.co.za",
                            FailedLoginAttempts = 0,
                            FirstName = "Gizara",
                            Gender = "Male",
                            HireDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Mkhize",
                            MustChangePassword = "False",
                            PasswordHash = "pharmacist123",
                            Role = "PHARMACIST",
                            UserName = "Pharmacist"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.HospitalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HospitalInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "456 Health Street, Cape Town",
                            ContactNumber = "021 123 4567",
                            Email = "info@localhospital.co.za",
                            HospitalName = "Local Community Hospital",
                            IsActive = "Active"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DosageForm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Schedule")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DosageForm = "Tablet",
                            IsActive = "Active",
                            Name = "Paracetamol",
                            Schedule = 1
                        },
                        new
                        {
                            Id = 2,
                            DosageForm = "Tablet",
                            IsActive = "Active",
                            Name = "Ibuprofen",
                            Schedule = 2
                        },
                        new
                        {
                            Id = 3,
                            DosageForm = "Injection",
                            IsActive = "Active",
                            Name = "Morphine",
                            Schedule = 5
                        },
                        new
                        {
                            Id = 4,
                            DosageForm = "Syrup",
                            IsActive = "Active",
                            Name = "Cough Syrup"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.MedicationAdministration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdministered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("MedicationId");

                    b.ToTable("MedicationAdministrations");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsRead")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellphoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsTwoFactorEnabled")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("MustChangePassword")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SouthAfricanIdNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CellphoneNumber = "0721234567",
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patient@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Alice",
                            HomeAddress = "123 Main Street, Cape Town",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Johnson",
                            MustChangePassword = "False",
                            PasswordHash = "patient123",
                            SouthAfricanIdNumber = "8001015009087",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.PatientMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.ToTable("PatientMovements");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PharmacistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescribedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ScriptManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ScriptStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PharmacistId");

                    b.HasIndex("ScriptManagerId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.StockTake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmployeeId");

                    b.ToTable("StockTakes");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.StockTakeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<int>("StockTakeId")
                        .HasColumnType("int");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.HasIndex("StockTakeId");

                    b.ToTable("StockTakeItems");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("IsTrusted")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Vitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("BloodSugarMmolL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HeartRateBpm")
                        .HasColumnType("int");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("int");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General admissions",
                            IsActive = "Active",
                            Name = "General Ward A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Post-operative care",
                            IsActive = "Active",
                            Name = "Surgical Ward"
                        });
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Admission", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "CreatedByWardAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByWardAdminId");

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseId");

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("CreatedByWardAdmin");

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionAllergy", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany("AdmissionAllergies")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Allergy");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionCondition", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany("AdmissionConditions")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.AdmissionMedication", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany("AdmissionMedications")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Bed", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.ConsumableOrder", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId");

                    b.Navigation("Consumable");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.DoctorVisit", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Admission");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.MedicationAdministration", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.PatientMovement", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany("PatientMovements")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Prescription", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId");

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "ScriptManager")
                        .WithMany()
                        .HasForeignKey("ScriptManagerId");

                    b.Navigation("Admission");

                    b.Navigation("Medication");

                    b.Navigation("Pharmacist");

                    b.Navigation("ScriptManager");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.StockTake", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Employee", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.StockTakeItem", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Consumable", "Consumable")
                        .WithMany()
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.StockTake", "StockTake")
                        .WithMany("StockTakeItems")
                        .HasForeignKey("StockTakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");

                    b.Navigation("StockTake");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Treatment", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Vitals", b =>
                {
                    b.HasOne("WARDMANAGEMENTSYSTEM.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Admission", b =>
                {
                    b.Navigation("AdmissionAllergies");

                    b.Navigation("AdmissionConditions");

                    b.Navigation("AdmissionMedications");

                    b.Navigation("PatientMovements");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.StockTake", b =>
                {
                    b.Navigation("StockTakeItems");
                });

            modelBuilder.Entity("WARDMANAGEMENTSYSTEM.Models.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
